Add protocol flag
Optable/match-cli pull request #19
Opened 2021-11-17 16:44 UTC by juanli16

2021-12-09 22:07 UTC, juanli16 reviewed
Minor comment but LGTM!

2021-12-09 22:07 UTC, juanli16 commented on pkg/match/psi.go
> +	zerolog.Ctx(ctx).Info().Msgf("negotiating protocol: %v", protocolStrings)
```suggestion
	zerolog.Ctx(ctx).Info().Msgf("negotiating protocol: %v", preferredProtocols)
```

2021-12-09 22:07 UTC, juanli16 commented on pkg/match/psi.go
> +	zerolog.Ctx(ctx).Info().Msgf("negotiating protocol: %v", protocolStrings)
String method should already take care of the formatting.

2021-12-10 01:45 UTC, xcapaldi commented on pkg/match/psi.go
> +	zerolog.Ctx(ctx).Info().Msgf("negotiating protocol: %v", protocolStrings)
You're right

2021-12-10 20:13 UTC, ratelle commented
Why did we choose to still proceed if the protocol request of the sender can't be fulfilled by the receiver. Shouldn't the sender fail? I think that would be the expectation of a cli user.

2021-12-10 22:10 UTC, ratelle commented on pkg/cli/match.go
> +		Protocol    string        `default:"dhpsi" enum:"bpsi,npsi,kkrtpsi,dhpsi" help:"Preferred PSI protocol"`
Match cli should only support dhpsi and kkrt

2021-12-10 22:16 UTC, ratelle requested changes
As mentioned, no fallback to dhpsi and no npsi and bpsi in the options.

2021-12-10 23:35 UTC, xcapaldi commented
> Why did we choose to still proceed if the protocol request of the sender can't be fulfilled by the receiver. Shouldn't the sender fail? I think that would be the expectation of a cli user.

Okay the negotiation procedure is updated so that the whole match attempt will fail if the sender requests an unsupported protocol

2021-12-13 16:14 UTC, ratelle approved these changes

2021-12-13 17:03 UTC, merged