Remove duplicate insight count from source audience
Optable/match-cli pull request #23
Opened 2021-12-07 00:52 UTC by HarmanpreetSinghGrover

ClickUp Task: https://app.clickup.com/t/1rwa35x

2021-12-07 15:21 UTC, juanli16 commented on pkg/cli/match.go
> +	n, nUnique, srcInsight, records, err := util.GenInputChannel(ctx, m.File)
We don't use `n` anymore.
Since, we are already only counting the unique IDs, should we also only pass the unique IDs to PSI?
This way it will reduce the amount of work done on duplicated IDs, and reduce the local memory usage. 
What do you think? @ratelle

2021-12-07 15:33 UTC, HarmanpreetSinghGrover commented on pkg/cli/match.go
> +	n, nUnique, srcInsight, records, err := util.GenInputChannel(ctx, m.File)
I think, we still use n (here: https://github.com/Optable/match-cli/blob/main/internal/util/util.go#L31). 
We compute the source audience and create an input channel in two separate functions. In the current implementation, we are ignoring duplicates only while counting the source audience, not while creating an input channel so we need n.

2021-12-07 15:58 UTC, juanli16 commented on pkg/cli/match.go
> +	n, nUnique, srcInsight, records, err := util.GenInputChannel(ctx, m.File)
that's the idea

2021-12-07 18:34 UTC, HarmanpreetSinghGrover commented on pkg/cli/match.go
> +	n, nUnique, srcInsight, records, err := util.GenInputChannel(ctx, m.File)
ok, I'll make the changes.

2021-12-09 14:59 UTC, juanli16 reviewed
Is there no way to just have one pass to the input file?

2021-12-09 14:59 UTC, juanli16 commented on internal/util/util.go
> +	if len(line) > 1 && line[len(line)-1] == '\n' {
`ReadBytes` returns an `err` if the bytes read does not end in the delimiter.
Meaning if you want to make sure `line` contains `\n`, check the error instead.

2021-12-15 16:16 UTC, juanli16 requested changes
I would add a new test to check that the output of `GetInputChannel` is the deduplicated version of the raw inputs

2021-12-15 19:13 UTC, juanli16 requested changes

2021-12-15 19:13 UTC, juanli16 commented on internal/util/util_test.go
> +	defer cancel()
You can avoid all these, by changing the signature of GetInputChannel to accept an `io.Reader`, instead of a file pointer. The reason why we used a file pointer is to be able to call `Seek`, after the first pass on the file with the `count` method. 
Here your artifact of `tmp/input_file.csv` will not get cleaned up.
You also don't need a context with timeout.

2021-12-15 19:21 UTC, HarmanpreetSinghGrover commented on internal/util/util_test.go
> +	defer cancel()
Ok! Will do

2021-12-15 19:56 UTC, juanli16 commented on internal/util/util_test.go
> +	}
```suggestion
	expectedOutput := map[string]bool{
		"i4:8.8.8.8": true,
		"p:18055554321": true,
		"i4:1.1.1.1": true,
		"i6:1.1.1.1.1.1": true,
		"p:12125551122": true,
		"e:920d0b248f5eea3b9c4838867d8dc8392e8522f2f89f7dc67a3f0e3d52ba2c14": true,
		"e:920d1212465e48d839b47102826b8c574959e5fcc6bf0fe4f888811a6d14c8de": true,
		"a:214as2d4asasdasd": true,
		"e:920d43ae6aebac63291f0476a63f9dc3d3cd7d3b071673c7f145f58e893740f4": true,
		"r:4as6d4a3s4dasdad": true,
		"g:a2354ds35as4d3asd": true,
		"g:5a4d35a4d35as4d3a": true,
		"f:21312230udklsjfaklhjda": true,
		"s:alhjklashsjklfahs23e0923ur420": true,
	}

	chanLength := int64(0)

	for identifier := range records {
		if _, ok := expectedOutput[string(identifier)]; !ok {
			t.Fatal("unexpected output")
		}
		chanLength++
	}
```

2021-12-15 19:56 UTC, juanli16 commented on internal/util/util_test.go
> +	}
remove `count`

2021-12-15 20:57 UTC, ratelle commented on internal/util/util.go
> +	n, elementsInFile, insight, err := count(f)
Why do we need count at this point? Seems like the code should be inlined here instead of returning 4 return values.

2021-12-15 21:23 UTC, ratelle commented on internal/util/util.go
> +	n, elementsInFile, insight, err := count(f)
Okay I've taken a better look at the code and I think we need to split that function a little bit. There's too much done here. Can we have a function that reads the entire file and deduplicate, a second function that counts the insights and finally a small function to get the channel. cc : @juanli16

2021-12-15 21:36 UTC, HarmanpreetSinghGrover commented on internal/util/util.go
> +	n, elementsInFile, insight, err := count(f)
Sure! Thanks for the feedback :)

2021-12-15 21:41 UTC, juanli16 commented on internal/util/util.go
> +	n, elementsInFile, insight, err := count(f)
It would make the code easier to follow. I agree.

2021-12-15 21:43 UTC, ratelle requested changes
As mentioned in the comments

2021-12-21 14:19 UTC, HarmanpreetSinghGrover commented on internal/util/util.go
> +	uniqueIdentifiersInFile := make(map[string]bool)
No, this map is used to remove invalid identifiers from the input file. 
So, unqiue Identifiers In File map = unique Elements In File map - Invalid Identifiers.

2022-01-28 17:19 UTC, juanli16 approved these changes

2022-01-28 19:08 UTC, ratelle approved these changes

2022-01-28 19:10 UTC, merged